---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "sleesh"
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "weekly"
    labels:
      - "npmmmsms"
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
      labels:
        - "bundlerr"
        - "nhdvvnhn"
